version: "3.7"

services:
  nfs:
    restart: "no"
    image: erichough/nfs-server
    volumes:
      - ./nfs-data/nfs:/nfs
      - ${APP_ROOT:-../app}:/nfs/lnmp/app
      - ./nfs-data/nfs/lnmp/mysql:/nfs/lnmp/mysql
      - ./nfs-data/nfs/lnmp/redis:/nfs/lnmp/redis
      - ./nfs-data/nfs/lnmp/registry:/nfs/lnmp/registry
      - ./nfs-data/nfs/lnmp/log:/nfs/lnmp/log
    env_file:
      - ./.env.example
      - ./.env
    # cap_add:
    #  - SYS_ADMIN
    privileged: true
    ports:
      # - "111:111"
      # - "111:111/udp"
      # nfs4 only need open 2049 port
      - "2049:2049"
      - "2049:2049/udp"
      # - "20048:20048"
      # - "20048:20048/udp"

volumes:
  nfs-volume:
