bases:
- ../../base
resources:
- pv.yaml
configMapGenerator:
- name: lnmp-redis-conf-0.0.1
  files:
  - redis.conf=config/redis.development.conf
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
generatorOptions:
  labels:
    app: lnmp
    tier: redis
  disableNameSuffixHash: true
