apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
  namespace: default
spec:
  ipFamily: IPv6
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 8080
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
