apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: lnmp-data
  labels:
    type: local
    app: lnmp
    tier: code-data
spec:
  capacity:
    storage: 20Gi
  accessModes:
    {{- if .Values.nfs.enabled -}}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.nfs.enabled -}}
  nfs:
    server: {{ .Values.nfs.server }}
    path: "/lnmp/app"
  storageClassName: slow
  {{- else }}
  hostPath:
    path: {{ .Values.app_root_pv }}
  storageClassName: hostpath
  {{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: lnmp-mysql-data
  labels:
    type: local
    app: lnmp
    tier: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    {{- if .Values.nfs.enabled -}}
    - ReadWriteMany    # 被单个节点mount为读写rw模式
    # - ReadOnlyMany   # 被多个节点mount为只读ro模式
    {{- else }}
    - ReadWriteOnce  # 被多个节点mount为读写rw模式
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  # Retain 允许用户手动回收
  # Recycle 删除 PV 上的数据
  # Delete 删除 PV
  {{- if .Values.nfs.enabled -}}
  nfs:
    # FIXME: use the right IP
    server: {{ .Values.nfs.server }}
    path: "/lnmp/mysql"
  storageClassName: slow
  {{- else }}
  hostPath:
    path: {{ .Values.mysql.pv_path }}
  storageClassName: hostpath
  {{- end }}
---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: lnmp-redis-data
  labels:
    type: local
    app: lnmp
    tier: redis
spec:
  capacity:
    storage: 20Gi
  accessModes:
    {{- if .Values.nfs.enabled -}}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.nfs.enabled -}}
  nfs:
    server: {{ .Values.nfs.server }}
    path: "/lnmp/redis"
  storageClassName: slow
  {{- else }}
  hostPath:
    path: {{ .Values.redis.pv_path }}
  storageClassName: hostpath
  {{- end }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ .Values.namespace }}
  name: lnmp-registry-data
  labels:
    type: local
    app: lnmp
    tier: registry
spec:
  capacity:
    storage: 20Gi
  accessModes:
    {{- if .Values.nfs.enabled -}}
    - ReadWriteMany
    {{- else }}
    - ReadWriteOnce
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.nfs.enabled -}}
  nfs:
    server: {{ .Values.nfs.server }}
    path: "/lnmp/registry"
  storageClassName: slow
  {{- else }}
  hostPath:
    path: {{ .Values.registry.pv_path }}
  storageClassName: hostpath
  {{- end }}
