apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-data
  labels:
    app: lnmp
    tier: code-data
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: code-data
  resources:
    requests:
      storage: 20Gi
  {{- if .Values.nfs.enabled }}
  storageClassName: slow
  accessModes: ["ReadWriteMany"]
  {{ else }}
  storageClassName: hostpath
  accessModes: ["ReadWriteOnce"]
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: lnmp-mysql-data
  labels:
    app: lnmp
    tier: mysql
spec:
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
    # matchExpressions:
      # - {key: environment, operator: In, values: [dev]}
  {{- if .Values.nfs.enabled }}
  storageClassName: slow
  accessModes: ["ReadWriteMany"]
  {{ else }}
  storageClassName: hostpath
  accessModes: ["ReadWriteOnce"]
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: lnmp-redis-data
  labels:
    app: lnmp
    tier: redis
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: redis
  resources:
    requests:
      storage: 20Gi
  {{- if .Values.nfs.enabled }}
  storageClassName: slow
  accessModes: ["ReadWriteMany"]
  {{ else }}
  storageClassName: hostpath
  accessModes: ["ReadWriteOnce"]
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-registry-data
  labels:
    app: lnmp
    tier: registry
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: registry
  resources:
    requests:
      storage: 20Gi
  {{- if .Values.nfs.enabled }}
  storageClassName: slow
  accessModes: ["ReadWriteMany"]
  {{ else }}
  storageClassName: hostpath
  accessModes: ["ReadWriteOnce"]
  {{- end }}
