apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: lnmp-env-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  TZ: {{ .Values.TZ }}
  APP_ENV: {{ .Values.APP_ENV }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: lnmp-redis-conf-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  redis.conf: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
