bases:
- ../../base
resources:
- pv.yaml
- lnmp-nginx.service.yaml
configMapGenerator:
- name: lnmp-nginx-conf-0.0.1
  files:
  - nginx.conf=config/nginx.custom.conf
  # - nginx.conf=config/nginx.development.conf
- name: lnmp-nginx-conf.d-0.0.1
  files:
  - config/conf.d/www.custom.conf
  # - config/conf.d/t.khs1994.com.development.conf
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
secretGenerator:
- name: lnmp-nginx-khs1994-com-tls-0.0.1
  files:
  - t.khs1994.com.crt=config/conf.d/ssl/t.khs1994.com.crt
  - t.khs1994.com.key=config/conf.d/ssl/t.khs1994.com.key
patches:
generatorOptions:
  labels:
    app: lnmp
    tier: nginx
