# sed "s#myclass#runcv1#g" deployment/runtimeClass/pod.yaml | kubectl apply -f -

kind: Pod
apiVersion: v1
metadata:
  name: test
  labels:
    lnmp: test
spec:
  runtimeClassName: myclass
  # runtimeClassName: runcv1
  # runtimeClassName: runclinux
  containers:
  - name: "lnmp-pod"
    image: "nginx:1.17.5-alpine"
    volumeMounts:
    - name: test
      mountPath: /opt/data
  # - name: "lnmp-pod2"
  #   image: khs1994/php:7.3.11-fpm-alpine
  volumes:
  - name: test
    emptyDir: {}
