kind: Pod
apiVersion: v1
metadata:
  name: test
  labels:
    lnmp: test
spec:
  runtimeClassName: myclass
  containers:
  - name: "lnmp-pod"
    image: "nginx:1.17.3-alpine"
    volumeMounts:
    - name: test
      mountPath: /opt/data
  # - name: "lnmp-pod2"
  #   image: khs1994/php:7.3.8-fpm-alpine
  volumes:
  - name: test
    emptyDir: {}
