resources:
- apiservice.yaml
- deployment.yaml
- pdb.yaml
- rbac.yaml
- service.yaml
images:
  - name: gcr.io/k8s-staging-metrics-server/metrics-server:master
    newName: ccr.ccs.tencentyun.com/khs1994/metrics-server
    newTag: master
