apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-database
spec:
  volumeClaimTemplates:
  - metadata:
      name: "database-data"
      labels:
        heritage: Helm
        release: RELEASE-NAME
        chart: harbor
        app: "harbor"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "1Gi"
      selector:
        matchLabels:
          app: harbor
          component: database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-redis
spec:
  template:
    spec:
      initContainers:
      - name: init
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        image: busybox
        args:
        - "sh"
        - "-c"
        - "chown 999:999 /var/lib/redis"
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
          subPath:
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        heritage: Helm
        release: RELEASE-NAME
        chart: harbor
        app: "harbor"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "1Gi"
      selector:
        matchLabels:
          app: harbor
          component: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: harbor-trivy
spec:
  template:
    spec:
      initContainers:
      - name: init
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        image: busybox
        args:
        - "sh"
        - "-c"
        - "chown 10000:10000 /home/scanner/.cache"
        volumeMounts:
          - name: data
            mountPath: /home/scanner/.cache
            subPath:
            readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        heritage: Helm
        release: RELEASE-NAME
        chart: harbor
        app: "harbor"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "5Gi"
      selector:
        matchLabels:
          app: harbor
          component: trivy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "harbor-registry"
spec:
  template:
    spec:
      initContainers:
      - name: init
        image: busybox
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        args:
        - "sh"
        - "-c"
        - "chown 10000:10000 /storage"
        volumeMounts:
        - name: registry-data
          mountPath: /storage
          subPath:
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: harbor-jobservice
spec:
  template:
    spec:
      initContainers:
      - name: chmod
        image: busybox
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - "chown 10000:10000 /var/log/jobs"
        volumeMounts:
        - name: job-logs
          mountPath: /var/log/jobs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "harbor-chartmuseum"
spec:
  template:
    spec:
      initContainers:
      - name: chmod
        image: busybox
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        imagePullPolicy: IfNotPresent
        args:
        - sh
        - -c
        - "chown 10000:10000 /chart_storage"
        volumeMounts:
        - name: chartmuseum-data
          mountPath: /chart_storage
          subPath:
