kind: Service
apiVersion: v1
metadata:
  name: registry
  labels:
    app: lnmp
    tier: registry
    version: 0.0.1
spec:
  # type: NodePort
  selector:
    app: lnmp
    tier: registry
    version: 0.0.1
  ports:
  - name: https
    protocol: TCP
    port: 443
    # nodePort: 443

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: registry
  labels:
    app: lnmp
    tier: registry
    version: 0.0.1
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: registry
      version: 0.0.1
  replicas: 1
  template:
    metadata:
      labels:
        app: lnmp
        tier: registry
        version: 0.0.1
    spec:
      containers:
      - name: registry
        image: registry
        ports:
        - containerPort: 443
        volumeMounts:
        - name: lnmp-registry-data
          mountPath: /var/lib/registry
        - name: lnmp-registry-conf
          mountPath: /etc/docker/registry/config.yml
          subPath: config.yml
        - name: lnmp-registry-tls
          mountPath: /etc/docker/registry/ssl
      volumes:
      - name: lnmp-registry-data
        persistentVolumeClaim:
          claimName: lnmp-registry-data
      - name: lnmp-registry-conf
        configMap:
          name: lnmp-registry-conf-0.0.1
          items:
          - key: config.yml
            path: config.yml
      - name: lnmp-registry-tls
        secret:
          secretName: lnmp-registry-tls-0.0.1
