apiVersion: v1
kind: Service
metadata:
  name: nginx
  # namespace: my-namespace
  labels:
    app: lnmp
    tier: frontend
spec:
  # externalIPs:
  #   - 192.168.57.110
  # 暴露服务方式之一
  type: LoadBalancer

  # 暴露服务方式之一
  # type: NodePort

  # 集群内的私有 ip ，this is default
  # type: ClusterIP
  # clusterIP: None

  # sessionAffinity: None

  # 定义标签选择器
  selector:
    app: lnmp
    tier: frontend

  ports:
  - name: https
    protocol: TCP
    port: 443
    # targetPort: 443
    # 通过访问 Service 的 port 端口转发到 Pod 的 targetPort 端口上

    # 暴露服务方式之一
    # 将 service 的 port 映射到每个 node 的一个指定内部 port 上，如果不指定 nodePort,k8s 将随机映射
    # nodePort: 443
  - name: http
    protocol: TCP
    port: 80
status:
  loadBalancer: {}
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lnmp-data
#   labels:
#     app: lnmp
#     tier: frontend
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lnmp-nginx-conf
#   labels:
#     app: lnmp
#     tier: frontend
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  # namespace: my-namespace
  labels:
    app: lnmp
    tier: frontend
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: frontend
  replicas: 2
  strategy: {}
  template:
    metadata:
      labels:
        app: lnmp
        tier: frontend
    spec:
      # nodeSelector:
      #   beta.kubernetes.io/arch: amd64
      #   beta.kubernetes.io/os: windows # linux
      #   kubernetes.io/hostname: coreos3
      containers:
      - name: lnmp-nginx
        image: khs1994/nginx:1.15.1-alpine
        imagePullPolicy: IfNotPresent # Always
        args:
        - nginx
        - -g
        - "daemon off;"
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: lnmp-env
        # - name: A
        #   value: a
        ports:
        - containerPort: 443
        - containerPort: 80
        # securityContext:
        #   privileged: true
        volumeMounts:
        - name: lnmp-data
          mountPath: /app
        - name: lnmp-nginx-conf-d
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: lnmp-nginx-khs1994-com-tls
          mountPath: /etc/nginx/conf.d/ssl
          readOnly: true
        # 挂载 secret configMap 为文件夹，默认会覆盖掉文件夹中的全部文件，通过以下配置，只挂载指定的文件
        - name: lnmp-nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe: # 探测应用是否处于健康状态，如果不健康则删除并重新创建容器
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
        readinessProbe: # 探测应用是否启动完成并且处于正常服务状态，如果不正常则不会接收来自Kubernetes Service的流量
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: lnmp-data
        hostPath:
          path: /data/lnmp/app
          # path: /host_mnt/c/90621/lnmp/app
          # path: /Users/khs1994/lnmp/app

      # 将 secret 挂载为文件
      - name: lnmp-nginx-khs1994-com-tls
        secret:
          secretName: lnmp-nginx-khs1994-com-tls
      - name: lnmp-nginx-conf
        secret:
          secretName: lnmp-nginx-conf
          items:
          - key: nginx
            path: nginx.conf
      - name: lnmp-nginx-conf-d
        secret:
          secretName: lnmp-nginx-conf-d
      restartPolicy: Always
      # dnsPolicy: ClusterFirst
status: {}
