apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: lnmp-mysql-data
  labels:
    app: lnmp
    tier: mysql
spec:
  accessModes:
    - ReadWriteMany
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
    # matchExpressions:
      # - {key: environment, operator: In, values: [dev]}
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: lnmp-redis-data
  labels:
    app: lnmp
    tier: redis
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: lnmp
      tier: redis
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: lnmp-data
  labels:
    app: lnmp
    tier: code-data
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: lnmp
      tier: code-data
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: lnmp-registry-data
  labels:
    app: lnmp
    tier: registry
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: lnmp
      tier: registry
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
