apiVersion: v1
kind: Service
metadata:
  name: php7
  labels:
    app: lnmp
spec:
  ports:
  - port: 9000
  selector:
    app: lnmp
    tier: php7
  clusterIP: None
status:
  loadBalancer: {}
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: php7
  labels:
    app: lnmp
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: php7
  replicas: 2
  strategy: {}
  template:
    metadata:
      labels:
        app: lnmp
        tier: php7
    spec:
      containers:
      - name: lnmp-php7
        image: khs1994/php-fpm:7.2.7-alpine3.7
        args:
        - php-fpm
        - -R
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: lnmp-env
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              key: APP_ENV
              name: lnmp-env
        ports:
        - name: lnmp-php7
          containerPort: 9000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: lnmp-data
          mountPath: /app
      volumes:
      # - name: lnmp-data
      #   persistentVolumeClaim:
      #     claimName: lnmp-data
      #
      - name: lnmp-data
        hostPath:
          path: /data/lnmp/app
      restartPolicy: Always
status: {}
