apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-env
  labels:
    app: lnmp
data:
  # kubectl create configmap special-config --from-literal=special.how=very
  # kubectl create configmap special-config --from-env-file=.env.example
  TZ: Asia/Shanghai
  APP_ENV: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-redis-conf
  labels:
    app: lnmp
data:
  redis-conf: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
