apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: lnmp
spec:
  ports:
  - name: https
    protocol: TCP
    port: 443
  - name: http
    protocol: TCP
    port: 80
  selector:
    app: lnmp
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lnmp-data
#   labels:
#     app: lnmp
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lnmp-nginx-conf
#   labels:
#     app: lnmp
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: lnmp
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: frontend
  replicas: 2
  strategy: {}
  template:
    metadata:
      labels:
        app: lnmp
        tier: frontend
    spec:
      containers:
      - image: khs1994/nginx:1.15.1-alpine
        name: lnmp-nginx
        args:
        - nginx
        - -g
        - "daemon off;"
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: lnmp-env
        ports:
        - containerPort: 443
        - containerPort: 80
          name: lnmp-nginx
        volumeMounts:
        - name: lnmp-data
          mountPath: /app
        - name: lnmp-nginx-conf-d
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: lnmp-nginx-khs1994-com-tls
          mountPath: /etc/nginx/conf.d/ssl
          readOnly: true
        - name: lnmp-nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        resources: {}
      volumes:
      - name: lnmp-data
        hostPath:
          path: /data/lnmp/app

      # 将 secret 挂载为文件
      - name: lnmp-nginx-khs1994-com-tls
        secret:
          secretName: lnmp-nginx-khs1994-com-tls
      - name: lnmp-nginx-conf
        secret:
          secretName: lnmp-nginx-conf
          items:
          - key: nginx
            path: nginx.conf
      - name: lnmp-nginx-conf-d
        secret:
          secretName: lnmp-nginx-conf-d
      restartPolicy: Always
status: {}
