apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: php7
  labels:
    app: lnmp
    tier: php7
    version: 0.0.1
spec:
  selector:
    app: lnmp
    tier: php7
    version: 0.0.1
  ports:
  - port: 9000
  clusterIP: None
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: php7
  labels:
    app: lnmp
    tier: php7
    version: 0.0.1
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: php7
      version: 0.0.1
  replicas: 2
  minReadySeconds: 5
  revisionHistoryLimit: 5 # 保留几个版本
  strategy:
    type: RollingUpdate # Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: lnmp
        tier: php7
        version: 0.0.1
    spec:
      containers:
      - name: lnmp-php7
        image: khs1994/php:7.2.9-fpm-alpine
        args:
        - php-fpm
        - -R
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: TZ
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: APP_ENV
        - name: APP_LOG
          valueFrom:
            configMapKeyRef:
              name: lnmp-env-0.0.1
              key: APP_LOG
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: lnmp-data
          mountPath: /app

        - name: lnmp-php-conf
          mountPath: /usr/local/etc/php/php.ini
          subPath: php.ini
        # - name: lnmp-php-conf
        #   mountPath: /usr/local/etc/php/conf.d/docker-xdebug.ini
        #   subPath: docker-xdebug.ini
        - name: lnmp-php-conf
          mountPath: /usr/local/etc/php-fpm.d/zz-docker.conf
          subPath: zz-docker.conf
        - name: lnmp-php-conf
          mountPath: /tmp/config.json
          subPath: config.json
      restartPolicy: Always
      volumes:
      - name: lnmp-data
        persistentVolumeClaim:
          claimName: lnmp-data
      - name: lnmp-php-conf
        configMap:
          name: lnmp-php-conf-0.0.1
          items:
          - key: php.ini
            path: php.ini
          # - key: docker-xdebug.ini
          #   path: docker-xdebug.ini
          - key: zz-docker.production.conf
            path: zz-docker.conf
          - key: composer.config.json
            path: config.json
