apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-mysql-data
  labels:
    type: local
    app: lnmp
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce    # 被单个节点mount为读写rw模式
    # - ReadOnlyMany   # 被多个节点mount为只读ro模式
    # - ReadWriteMany  # 被多个节点mount为读写rw模式
  persistentVolumeReclaimPolicy: Recycle
  # Retain 允许用户手动回收
  # Recycle 删除 PV 上的数据
  # Delete 删除 PV
  hostPath:
    path: /tmp/data/pv-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-redis-data
  labels:
    type: local
    app: lnmp
spec:
  capacity:
    storage: 20Gi
  accessModes: [ "ReadWriteOnce"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/pv-2
---
# PHP Project Data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-data
  labels:
    type: local
    app: lnmp
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/pv-3
---
# Nginx Config Files Data
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-nginx-conf
  labels:
    type: local
    app: lnmp
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle  
  hostPath:
    path: /tmp/data/pv-4
