apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: lnmp
spec:
  ports:
    - port: 3306
  selector:
    app: lnmp
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-mysql-data
  labels:
    app: lnmp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: lnmp
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lnmp
        tier: mysql
    spec:
      containers:
      - name: lnmp-mysql
        image: mysql:8.0.11
        # envFrom:
        #   - configMapKeyRef:
        #       name: env-config
        env:
        # 将 secret 变为环境变量
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lnmp-mysql-password
              key: password
        # config 用作环境变量
        - name: TZ
          valueFrom:
             configMapKeyRef:
               name: lnmp-env
               key: TZ
        - name: MYSQL_DATABASE
          value: test
        ports:
        - name: lnmp-mysql
          containerPort: 3306
        volumeMounts:
        - name: lnmp-mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: lnmp-mysql-data
        persistentVolumeClaim:
          claimName: lnmp-mysql-data
      restartPolicy: Always
