apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: mysql
  labels:
    app: lnmp
    tier: mysql
spec:
  selector:
    app: lnmp
    tier: mysql
  ports:
    - port: 3306
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: lnmp-mysql-data
  labels:
    app: lnmp
    tier: mysql
spec:
  accessModes:
    - ReadWriteOnce
  # volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
    # matchExpressions:
      # - {key: environment, operator: In, values: [dev]}
  storageClassName: hostpath
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: mysql
  labels:
    app: lnmp
    tier: mysql
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lnmp
        tier: mysql
    spec:
      containers:
      - name: lnmp-mysql
        image: mysql:8.0.12
        imagePullPolicy: IfNotPresent
        # envFrom:
        #   - configMapKeyRef:
        #       name: env-config
        env:
        # 将 secret 变为环境变量
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lnmp-mysql-password
              key: password
        # config 用作环境变量
        - name: TZ
          valueFrom:
             configMapKeyRef:
               name: lnmp-env
               key: TZ
        - name: MYSQL_DATABASE
          value: test
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: lnmp-mysql-data
          mountPath: /var/lib/mysql
        - name: lnmp-mysql-cnf
          mountPath: /etc/mysql/conf.d/docker.cnf
          subPath: my.cnf
      volumes:
      - name: lnmp-mysql-data
        persistentVolumeClaim:
          claimName: lnmp-mysql-data
      - name: lnmp-mysql-cnf
        configMap:
          name: lnmp-mysql-cnf
          items:
          - key: my.cnf
            path: my.cnf

      restartPolicy: Always
