apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: lnmp
    tier: frontend
spec:
  # type: NodePort
  # 这里定义标签选择器
  selector:
    app: lnmp
    tier: frontend

  ports:
  - name: https
    protocol: TCP
    port: 443
    # targetPort: 80
    # nodePort: 28888
  - name: http
    protocol: TCP
    port: 80
  type: LoadBalancer
status:
  loadBalancer: {}
---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lnmp-data
#   labels:
#     app: lnmp
#     tier: frontend
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: lnmp-nginx-conf
#   labels:
#     app: lnmp
#     tier: frontend
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 20Gi
# ---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: lnmp
    tier: frontend
spec:
  selector:
    matchLabels:
      app: lnmp
      tier: frontend
  replicas: 2
  strategy: {}
  template:
    metadata:
      labels:
        app: lnmp
        tier: frontend
    spec:
      containers:
      - name: lnmp-nginx
        image: khs1994/nginx:1.15.1-alpine
        imagePullPolicy: IfNotPresent
        args:
        - nginx
        - -g
        - "daemon off;"
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: lnmp-env
        ports:
        - containerPort: 443
        - containerPort: 80
        # securityContext:
        #   privileged: true
        volumeMounts:
        - name: lnmp-data
          mountPath: /app
        - name: lnmp-nginx-conf-d
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: lnmp-nginx-khs1994-com-tls
          mountPath: /etc/nginx/conf.d/ssl
          readOnly: true
        - name: lnmp-nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: lnmp-data
        hostPath:
          path: /data/lnmp/app
          # path: /host_mnt/c/90621/lnmp/app
          # path: /Users/khs1994/lnmp/app

      # 将 secret 挂载为文件
      - name: lnmp-nginx-khs1994-com-tls
        secret:
          secretName: lnmp-nginx-khs1994-com-tls
      - name: lnmp-nginx-conf
        secret:
          secretName: lnmp-nginx-conf
          items:
          - key: nginx
            path: nginx.conf
      - name: lnmp-nginx-conf-d
        secret:
          secretName: lnmp-nginx-conf-d
      restartPolicy: Always
status: {}
