apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-data
  labels:
    type: local
    app: lnmp
    tier: code-data
spec:
  capacity:
    storage: 20Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/username/app
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-mysql-data
  labels:
    type: local
    app: lnmp
    tier: mysql
spec:
  capacity:
    storage: 20Gi
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode
  volumeMode: Filesystem # or raw Block
  accessModes:
    # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

    - ReadWriteOnce    # 被单个节点mount为读写rw模式 RWO
                       # the volume can be mounted as read-write by a single node
    # - ReadOnlyMany   # 被多个节点mount为只读ro模式 ROX
                       # the volume can be mounted read-only by many nodes
    # - ReadWriteMany  # 被多个节点mount为读写rw模式 RWX
                       # the volume can be mounted as read-write by many nodes
  persistentVolumeReclaimPolicy: Retain
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#reclaiming
  # Retain 允许用户手动回收
  # Recycle 删除 PV 上的数据 deprecated
  # Delete 删除 PV
  hostPath:
    path: /var/lib/lnmp/mysql
  storageClassName: hostpath

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-redis-data
  labels:
    type: local
    app: lnmp
    tier: redis
spec:
  capacity:
    storage: 20Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/lnmp/redis
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-registry-data
  labels:
    type: local
    app: lnmp
    tier: registry
spec:
  capacity:
    storage: 20Gi
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/lib/lnmp/registry
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lnmp-log
  labels:
    type: local
    app: lnmp
    tier: log
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/log
  storageClassName: hostpath
