apiVersion: v1
kind: CronJob
metadata:
  namespace: default
  name: lnmp-cron
  labels:
    app: lnmp
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lnmp-cron
            image: khs1994/php:7.2.9-fpm-alpine
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
