# 可以运行 Laravel 调度器 Schedule

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: default
  name: lnmp-cron-0.0.1
  labels:
    app: lnmp
    version: 0.0.1
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lnmp-cron-0.0.1
            image: khs1994/php:7.2.9-fpm-alpine
            args:
            - /bin/sh
            - -c
            # - date; echo Hello from the Kubernetes cluster
            - php /app/laravel/artisan schedule:run
            volumeMounts:
            - name: lnmp-data
              mountPath: /app
          volumes:
          - name: lnmp-data
            persistentVolumeClaim:
              claimName: lnmp-data
          # restartPolicy: OnFailure
