nameOverride: "registry"
fullnameOverride: "fullname"

TZ: Asia/Shanghai

APP_ENV: production

platform: Linux
# platform: windows
# platform: Darwin

domain: t.khs1994.com

nfs:
  enabled: false
  server: 192.168.199.100

registry:
  image: registry:latest
