apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-mysql-data
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    $patch: delete
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: mysql
      env: production
  storageClassName: "hostpath"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lnmp-log
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    $patch: delete
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: lnmp
      tier: log
      env: production
  storageClassName: "hostpath"
