kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  template:
    spec:
      volumes:
        - name: lnmp-mysql-cnf
          configMap:
            name: lnmp-mysql-cnf-prod-0.0.1
            items:
            - key: docker.cnf
              path: docker.cnf
