bases:
- ../../base
resources:
- pvc.yaml
configMapGenerator:
- name: lnmp-redis-conf-0.0.1
  files:
  - redis.conf=config/redis.production.conf
- name: lnmp-tz
  literals:
  - TZ=Asia/Shanghai
patches:
# - hostpath.patch.yaml
generatorOptions:
  labels:
    app: lnmp
    tier: redis
