version: '3.7'

services:

  server:
    image: khs1994/coreos:server
    env_file:
      - ./.env.example
      - ./.env
    volumes:
      - ./cert:/srv/www/coreos/cert
      - ./current:/srv/www/coreos/current
      - ./disk:/srv/www/coreos/disk
      - ./pxe:/srv/www/coreos/pxe
      - ./kubernetes-release:/srv/www/coreos/kubernetes-release
    ports:
      - "8080:80"

  cfssl:
    image: khs1994/coreos:cert
    volumes:
      - ./cert:/srv/cfssl
      - ./cfssl/docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - ./.env.example
      - ./.env

  cfssl-single:
    image: khs1994/coreos:cert
    volumes:
      - ../systemd/certs:/srv/cfssl
      - ./cfssl/docker-entrypoint.sh:/docker-entrypoint.sh
    env_file:
      - ../systemd/.env.example
