apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lnmp-mysql-password-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  password: {{ .Values.mysql.password | b64enc }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lnmp-nginx-khs1994-com-tls-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  t.khs1994.com.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.production/t.khs1994.com.crt" | b64enc }}
  t.khs1994.com.key: {{ .Files.Get "config/nginx/conf.d/ssl.production/t.khs1994.com.key" | b64enc}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: lnmp-ingress-tls-{{ .Chart.Version }}
  labels:
    app: lnmp
    version: {{ .Chart.Version }}
data:
  tls.crt: |-
    {{ .Files.Get "config/nginx/conf.d/ssl.production/t.khs1994.com.crt" | b64enc }}
  tls.key: {{ .Files.Get "config/nginx/conf.d/ssl.production/t.khs1994.com.key" | b64enc}}
