apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    test: "true"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.15.1-alpine
        ports:
        - containerPort: 80
