secretGenerator:
  - name: harbor-notary-server
    files:
    - ca.crt
    - tls.crt
    - tls.key
    - server.json
    - signer.json
commonLabels:
  app: "harbor"
  component: notary
generatorOptions:
  disableNameSuffixHash: true
