bases:
  - ../linux
patchesJson6902:
  - path: patch-app.json
    target:
      group: ""
      kind: PersistentVolume
      name: lnmp-app-development
      version: v1
  - path: patch-mysql.json
    target:
      group: ""
      kind: PersistentVolume
      name: lnmp-mysql-data-development
      version: v1
  - path: patch-redis.json
    target:
      group: ""
      kind: PersistentVolume
      name: lnmp-redis-data-development
      version: v1
  - path: patch-log.json
    target:
      group: ""
      kind: PersistentVolume
      name: lnmp-log-development
      version: v1
