# commonLabels:
#   app: lnmp
# commonAnnotations:
#   app: lnmp
bases:
  - ../../base
resources:
- pv.yaml
patches:
  - lnmp-mysql.yaml
configMapGenerator:
- name: lnmp-mysql-cnf-0.0.1
  files:
  # - docker.cnf=config/docker.custom.cnf
  - docker.cnf=config/docker.development.cnf
secretGenerator:
- name: lnmp-mysql-password-0.0.1
  literals:
  - password=mytest
