resources:
- tekton.yaml
- dashboard.yaml
# configMapGenerator:
#   - name: config-artifact-bucket
#     namespace: tekton-pipelines
#     literals:
#       - location=gs://bucket-name
#       - location=s3://mybucket
#       - bucket.service.account.secret.name=tekton-storage
#       - bucket.service.account.secret.key=boto-config
#       - bucket.service.account.field.name=BOTO_CONFIG
#   - name: config-artifact-pvc
#     namespace: tekton-pipelines
#     literals:
#       - size=5Gi
#       - storageClassName=storage-class-name
# secretGenerator:
#   - name: tekton-storage
#     namespace: tekton-pipelines
#     type: kubernetes.io/opaque
#     files:
#       - boto-config
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:4175d6237de3f85d4cfa2e331e244f0b1c20776455af10dcccdb81a3f9ebb012
    newName: ccr.ccs.tencentyun.com/khs1994/tektoncd-dashboard
    digest: sha256:4175d6237de3f85d4cfa2e331e244f0b1c20776455af10dcccdb81a3f9ebb012
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.15.2@sha256:ef0f1858607e176a5393bcbf043b9276b0ba6c03ad4f157ff379c558bf00732e
    newName: ccr.ccs.tencentyun.com/khs1994/tektoncd-webhook
    newTag: v0.15.2@sha256:ef0f1858607e176a5393bcbf043b9276b0ba6c03ad4f157ff379c558bf00732e
  - name: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.15.2@sha256:3b9194dbb1ec6282469e1371abb52dce4f462706d08469d29893550f3e2debdf
    newName: ccr.ccs.tencentyun.com/khs1994/tektoncd-controller
    newTag: v0.15.2@sha256:3b9194dbb1ec6282469e1371abb52dce4f462706d08469d29893550f3e2debdf
    digest: sha256:3b9194dbb1ec6282469e1371abb52dce4f462706d08469d29893550f3e2debdf
