on:
  push:
    branches:
    - master
    paths:
    - '/docs/*'
    - '/docs/*/*'

name: Build Docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: docs-build
      uses: docker://pcit/vuepress
      env:
        PCIT_LOCAL_DIR: docs
      with:
        args: build
    - name: docs-sync
      uses: docker://pcit/pages
      env:
        PCIT_EMAIL: khs1994@khs1994.com
        PCIT_GIT_TOKEN: ${{ secrets.PCIT_GIT_TOKEN }}
        PCIT_GIT_URL: github.com/khs1994-docker/lnmp-k8s
        PCIT_KEEP_HISTORY: "1"
        PCIT_LOCAL_DIR: docs/.vuepress/dist
        PCIT_MESSAGE: Build docs by vuepress, Upload docs by PCIT
        PCIT_TARGET_BRANCH: gh-pages
        PCIT_USERNAME: khs1994
